services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: supply-chain-saga-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5434:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports: ["6379:6379"]
  nats:
    image: nats:2
    ports: ["4222:4222"]
  orders-svc:
    build: ./orders-svc
    env_file:
      - ./orders-svc/.env
    depends_on:
      - postgres
      - redis
      - nats
    ports:
      - "3001:3001"
  inventory-svc:
    build: ./inventory-svc
    env_file:
      - ./inventory-svc/.env
      - ./inventory-svc/.env.docker   # ensures DB_HOST=postgres in container
    depends_on:
      - postgres
    ports:
      - "3002:3002"
  payments-svc:
    build: ./payments-svc
    env_file:
      - ./payments-svc/.env
    depends_on:
      - postgres
      - redis
      - nats
    ports:
      - "3003:3003"
  shipping-svc:
    build: ./shipping-svc
    env_file:
      - ./shipping-svc/.env
      - ./shipping-svc/.env.docker
    depends_on:
      - postgres
    ports:
      - "3004:3004"

volumes:
  pgdata:
